// Vendored from kRPC (https://github.com/krpc/krpc), file protobuf/krpc.proto,
// fetched 2026-07-19 from branch `main`. kRPC's core is LGPL-3.0; this schema
// file defines the wire protocol. It is reproduced here VERBATIM except for the
// single added `option go_package` line (marked below), which upstream omits
// because it ships no Go client. Regenerate the Go bindings with:
//
//   protoc --go_out=. --go_opt=module=github.com/cpuchip/ksp-hmi \
//     -Ikrpc/proto krpc/proto/krpc.proto
//
// A network client of the (L)GPL kRPC mod is not a derivative work, so our own
// client code is licensed Apache-2.0 (see repo root). This schema stays under
// kRPC's terms.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: krpc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionRequest_Type int32

const (
	ConnectionRequest_RPC    ConnectionRequest_Type = 0
	ConnectionRequest_STREAM ConnectionRequest_Type = 1
)

// Enum value maps for ConnectionRequest_Type.
var (
	ConnectionRequest_Type_name = map[int32]string{
		0: "RPC",
		1: "STREAM",
	}
	ConnectionRequest_Type_value = map[string]int32{
		"RPC":    0,
		"STREAM": 1,
	}
)

func (x ConnectionRequest_Type) Enum() *ConnectionRequest_Type {
	p := new(ConnectionRequest_Type)
	*p = x
	return p
}

func (x ConnectionRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_krpc_proto_enumTypes[0].Descriptor()
}

func (ConnectionRequest_Type) Type() protoreflect.EnumType {
	return &file_krpc_proto_enumTypes[0]
}

func (x ConnectionRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionRequest_Type.Descriptor instead.
func (ConnectionRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{0, 0}
}

type ConnectionResponse_Status int32

const (
	ConnectionResponse_OK                ConnectionResponse_Status = 0
	ConnectionResponse_MALFORMED_MESSAGE ConnectionResponse_Status = 1
	ConnectionResponse_TIMEOUT           ConnectionResponse_Status = 2
	ConnectionResponse_WRONG_TYPE        ConnectionResponse_Status = 3
)

// Enum value maps for ConnectionResponse_Status.
var (
	ConnectionResponse_Status_name = map[int32]string{
		0: "OK",
		1: "MALFORMED_MESSAGE",
		2: "TIMEOUT",
		3: "WRONG_TYPE",
	}
	ConnectionResponse_Status_value = map[string]int32{
		"OK":                0,
		"MALFORMED_MESSAGE": 1,
		"TIMEOUT":           2,
		"WRONG_TYPE":        3,
	}
)

func (x ConnectionResponse_Status) Enum() *ConnectionResponse_Status {
	p := new(ConnectionResponse_Status)
	*p = x
	return p
}

func (x ConnectionResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_krpc_proto_enumTypes[1].Descriptor()
}

func (ConnectionResponse_Status) Type() protoreflect.EnumType {
	return &file_krpc_proto_enumTypes[1]
}

func (x ConnectionResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionResponse_Status.Descriptor instead.
func (ConnectionResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{1, 0}
}

type Procedure_GameScene int32

const (
	Procedure_SPACE_CENTER     Procedure_GameScene = 0
	Procedure_FLIGHT           Procedure_GameScene = 1
	Procedure_TRACKING_STATION Procedure_GameScene = 2
	Procedure_EDITOR_VAB       Procedure_GameScene = 3
	Procedure_EDITOR_SPH       Procedure_GameScene = 4
	Procedure_MISSION_BUILDER  Procedure_GameScene = 5
)

// Enum value maps for Procedure_GameScene.
var (
	Procedure_GameScene_name = map[int32]string{
		0: "SPACE_CENTER",
		1: "FLIGHT",
		2: "TRACKING_STATION",
		3: "EDITOR_VAB",
		4: "EDITOR_SPH",
		5: "MISSION_BUILDER",
	}
	Procedure_GameScene_value = map[string]int32{
		"SPACE_CENTER":     0,
		"FLIGHT":           1,
		"TRACKING_STATION": 2,
		"EDITOR_VAB":       3,
		"EDITOR_SPH":       4,
		"MISSION_BUILDER":  5,
	}
)

func (x Procedure_GameScene) Enum() *Procedure_GameScene {
	p := new(Procedure_GameScene)
	*p = x
	return p
}

func (x Procedure_GameScene) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Procedure_GameScene) Descriptor() protoreflect.EnumDescriptor {
	return file_krpc_proto_enumTypes[2].Descriptor()
}

func (Procedure_GameScene) Type() protoreflect.EnumType {
	return &file_krpc_proto_enumTypes[2]
}

func (x Procedure_GameScene) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Procedure_GameScene.Descriptor instead.
func (Procedure_GameScene) EnumDescriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{12, 0}
}

type Type_TypeCode int32

const (
	Type_NONE Type_TypeCode = 0
	// Values
	Type_DOUBLE Type_TypeCode = 1
	Type_FLOAT  Type_TypeCode = 2
	Type_SINT32 Type_TypeCode = 3
	Type_SINT64 Type_TypeCode = 4
	Type_UINT32 Type_TypeCode = 5
	Type_UINT64 Type_TypeCode = 6
	Type_BOOL   Type_TypeCode = 7
	Type_STRING Type_TypeCode = 8
	Type_BYTES  Type_TypeCode = 9
	// Objects
	Type_CLASS       Type_TypeCode = 100
	Type_ENUMERATION Type_TypeCode = 101
	// Messages
	Type_EVENT          Type_TypeCode = 200
	Type_PROCEDURE_CALL Type_TypeCode = 201
	Type_STREAM         Type_TypeCode = 202
	Type_STATUS         Type_TypeCode = 203
	Type_SERVICES       Type_TypeCode = 204
	// Collections
	Type_TUPLE      Type_TypeCode = 300
	Type_LIST       Type_TypeCode = 301
	Type_SET        Type_TypeCode = 302
	Type_DICTIONARY Type_TypeCode = 303
)

// Enum value maps for Type_TypeCode.
var (
	Type_TypeCode_name = map[int32]string{
		0:   "NONE",
		1:   "DOUBLE",
		2:   "FLOAT",
		3:   "SINT32",
		4:   "SINT64",
		5:   "UINT32",
		6:   "UINT64",
		7:   "BOOL",
		8:   "STRING",
		9:   "BYTES",
		100: "CLASS",
		101: "ENUMERATION",
		200: "EVENT",
		201: "PROCEDURE_CALL",
		202: "STREAM",
		203: "STATUS",
		204: "SERVICES",
		300: "TUPLE",
		301: "LIST",
		302: "SET",
		303: "DICTIONARY",
	}
	Type_TypeCode_value = map[string]int32{
		"NONE":           0,
		"DOUBLE":         1,
		"FLOAT":          2,
		"SINT32":         3,
		"SINT64":         4,
		"UINT32":         5,
		"UINT64":         6,
		"BOOL":           7,
		"STRING":         8,
		"BYTES":          9,
		"CLASS":          100,
		"ENUMERATION":    101,
		"EVENT":          200,
		"PROCEDURE_CALL": 201,
		"STREAM":         202,
		"STATUS":         203,
		"SERVICES":       204,
		"TUPLE":          300,
		"LIST":           301,
		"SET":            302,
		"DICTIONARY":     303,
	}
)

func (x Type_TypeCode) Enum() *Type_TypeCode {
	p := new(Type_TypeCode)
	*p = x
	return p
}

func (x Type_TypeCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type_TypeCode) Descriptor() protoreflect.EnumDescriptor {
	return file_krpc_proto_enumTypes[3].Descriptor()
}

func (Type_TypeCode) Type() protoreflect.EnumType {
	return &file_krpc_proto_enumTypes[3]
}

func (x Type_TypeCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type_TypeCode.Descriptor instead.
func (Type_TypeCode) EnumDescriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{18, 0}
}

type ConnectionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             ConnectionRequest_Type `protobuf:"varint,1,opt,name=type,proto3,enum=krpc.schema.ConnectionRequest_Type" json:"type,omitempty"`
	ClientName       string                 `protobuf:"bytes,2,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientIdentifier []byte                 `protobuf:"bytes,3,opt,name=client_identifier,json=clientIdentifier,proto3" json:"client_identifier,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConnectionRequest) Reset() {
	*x = ConnectionRequest{}
	mi := &file_krpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionRequest) ProtoMessage() {}

func (x *ConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionRequest.ProtoReflect.Descriptor instead.
func (*ConnectionRequest) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionRequest) GetType() ConnectionRequest_Type {
	if x != nil {
		return x.Type
	}
	return ConnectionRequest_RPC
}

func (x *ConnectionRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *ConnectionRequest) GetClientIdentifier() []byte {
	if x != nil {
		return x.ClientIdentifier
	}
	return nil
}

type ConnectionResponse struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	Status           ConnectionResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=krpc.schema.ConnectionResponse_Status" json:"status,omitempty"`
	Message          string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ClientIdentifier []byte                    `protobuf:"bytes,3,opt,name=client_identifier,json=clientIdentifier,proto3" json:"client_identifier,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConnectionResponse) Reset() {
	*x = ConnectionResponse{}
	mi := &file_krpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionResponse) ProtoMessage() {}

func (x *ConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionResponse.ProtoReflect.Descriptor instead.
func (*ConnectionResponse) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectionResponse) GetStatus() ConnectionResponse_Status {
	if x != nil {
		return x.Status
	}
	return ConnectionResponse_OK
}

func (x *ConnectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConnectionResponse) GetClientIdentifier() []byte {
	if x != nil {
		return x.ClientIdentifier
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Calls         []*ProcedureCall       `protobuf:"bytes,1,rep,name=calls,proto3" json:"calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_krpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetCalls() []*ProcedureCall {
	if x != nil {
		return x.Calls
	}
	return nil
}

type ProcedureCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Procedure     string                 `protobuf:"bytes,2,opt,name=procedure,proto3" json:"procedure,omitempty"`
	ServiceId     uint32                 `protobuf:"varint,4,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ProcedureId   uint32                 `protobuf:"varint,5,opt,name=procedure_id,json=procedureId,proto3" json:"procedure_id,omitempty"`
	Arguments     []*Argument            `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcedureCall) Reset() {
	*x = ProcedureCall{}
	mi := &file_krpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcedureCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcedureCall) ProtoMessage() {}

func (x *ProcedureCall) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcedureCall.ProtoReflect.Descriptor instead.
func (*ProcedureCall) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{3}
}

func (x *ProcedureCall) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ProcedureCall) GetProcedure() string {
	if x != nil {
		return x.Procedure
	}
	return ""
}

func (x *ProcedureCall) GetServiceId() uint32 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *ProcedureCall) GetProcedureId() uint32 {
	if x != nil {
		return x.ProcedureId
	}
	return 0
}

func (x *ProcedureCall) GetArguments() []*Argument {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type Argument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      uint32                 `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Argument) Reset() {
	*x = Argument{}
	mi := &file_krpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Argument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Argument) ProtoMessage() {}

func (x *Argument) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Argument.ProtoReflect.Descriptor instead.
func (*Argument) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{4}
}

func (x *Argument) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Argument) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Results       []*ProcedureResult     `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_krpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{5}
}

func (x *Response) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Response) GetResults() []*ProcedureResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ProcedureResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcedureResult) Reset() {
	*x = ProcedureResult{}
	mi := &file_krpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcedureResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcedureResult) ProtoMessage() {}

func (x *ProcedureResult) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcedureResult.ProtoReflect.Descriptor instead.
func (*ProcedureResult) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{6}
}

func (x *ProcedureResult) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ProcedureResult) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StackTrace    string                 `protobuf:"bytes,4,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_krpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{7}
}

func (x *Error) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Error) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Error) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Error) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

type StreamUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*StreamResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamUpdate) Reset() {
	*x = StreamUpdate{}
	mi := &file_krpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamUpdate) ProtoMessage() {}

func (x *StreamUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamUpdate.ProtoReflect.Descriptor instead.
func (*StreamUpdate) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{8}
}

func (x *StreamUpdate) GetResults() []*StreamResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type StreamResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Result        *ProcedureResult       `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResult) Reset() {
	*x = StreamResult{}
	mi := &file_krpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResult) ProtoMessage() {}

func (x *StreamResult) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResult.ProtoReflect.Descriptor instead.
func (*StreamResult) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{9}
}

func (x *StreamResult) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StreamResult) GetResult() *ProcedureResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type Services struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*Service             `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Services) Reset() {
	*x = Services{}
	mi := &file_krpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Services) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Services) ProtoMessage() {}

func (x *Services) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Services.ProtoReflect.Descriptor instead.
func (*Services) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{10}
}

func (x *Services) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type Service struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Procedures       []*Procedure           `protobuf:"bytes,2,rep,name=procedures,proto3" json:"procedures,omitempty"`
	Classes          []*Class               `protobuf:"bytes,3,rep,name=classes,proto3" json:"classes,omitempty"`
	Enumerations     []*Enumeration         `protobuf:"bytes,4,rep,name=enumerations,proto3" json:"enumerations,omitempty"`
	Exceptions       []*Exception           `protobuf:"bytes,5,rep,name=exceptions,proto3" json:"exceptions,omitempty"`
	Documentation    string                 `protobuf:"bytes,6,opt,name=documentation,proto3" json:"documentation,omitempty"`
	Deprecated       bool                   `protobuf:"varint,7,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	DeprecatedReason string                 `protobuf:"bytes,8,opt,name=deprecated_reason,json=deprecatedReason,proto3" json:"deprecated_reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_krpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{11}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetProcedures() []*Procedure {
	if x != nil {
		return x.Procedures
	}
	return nil
}

func (x *Service) GetClasses() []*Class {
	if x != nil {
		return x.Classes
	}
	return nil
}

func (x *Service) GetEnumerations() []*Enumeration {
	if x != nil {
		return x.Enumerations
	}
	return nil
}

func (x *Service) GetExceptions() []*Exception {
	if x != nil {
		return x.Exceptions
	}
	return nil
}

func (x *Service) GetDocumentation() string {
	if x != nil {
		return x.Documentation
	}
	return ""
}

func (x *Service) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *Service) GetDeprecatedReason() string {
	if x != nil {
		return x.DeprecatedReason
	}
	return ""
}

type Procedure struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Parameters       []*Parameter           `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`
	ReturnType       *Type                  `protobuf:"bytes,3,opt,name=return_type,json=returnType,proto3" json:"return_type,omitempty"`
	ReturnIsNullable bool                   `protobuf:"varint,4,opt,name=return_is_nullable,json=returnIsNullable,proto3" json:"return_is_nullable,omitempty"`
	GameScenes       []Procedure_GameScene  `protobuf:"varint,6,rep,packed,name=game_scenes,json=gameScenes,proto3,enum=krpc.schema.Procedure_GameScene" json:"game_scenes,omitempty"`
	Documentation    string                 `protobuf:"bytes,5,opt,name=documentation,proto3" json:"documentation,omitempty"`
	Deprecated       bool                   `protobuf:"varint,7,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	DeprecatedReason string                 `protobuf:"bytes,8,opt,name=deprecated_reason,json=deprecatedReason,proto3" json:"deprecated_reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Procedure) Reset() {
	*x = Procedure{}
	mi := &file_krpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Procedure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Procedure) ProtoMessage() {}

func (x *Procedure) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Procedure.ProtoReflect.Descriptor instead.
func (*Procedure) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{12}
}

func (x *Procedure) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Procedure) GetParameters() []*Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Procedure) GetReturnType() *Type {
	if x != nil {
		return x.ReturnType
	}
	return nil
}

func (x *Procedure) GetReturnIsNullable() bool {
	if x != nil {
		return x.ReturnIsNullable
	}
	return false
}

func (x *Procedure) GetGameScenes() []Procedure_GameScene {
	if x != nil {
		return x.GameScenes
	}
	return nil
}

func (x *Procedure) GetDocumentation() string {
	if x != nil {
		return x.Documentation
	}
	return ""
}

func (x *Procedure) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *Procedure) GetDeprecatedReason() string {
	if x != nil {
		return x.DeprecatedReason
	}
	return ""
}

type Parameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          *Type                  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	DefaultValue  []byte                 `protobuf:"bytes,3,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Nullable      bool                   `protobuf:"varint,4,opt,name=nullable,proto3" json:"nullable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	mi := &file_krpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{13}
}

func (x *Parameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Parameter) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Parameter) GetDefaultValue() []byte {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

func (x *Parameter) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

type Class struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Documentation    string                 `protobuf:"bytes,2,opt,name=documentation,proto3" json:"documentation,omitempty"`
	Deprecated       bool                   `protobuf:"varint,3,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	DeprecatedReason string                 `protobuf:"bytes,4,opt,name=deprecated_reason,json=deprecatedReason,proto3" json:"deprecated_reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Class) Reset() {
	*x = Class{}
	mi := &file_krpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Class) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Class) ProtoMessage() {}

func (x *Class) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Class.ProtoReflect.Descriptor instead.
func (*Class) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{14}
}

func (x *Class) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Class) GetDocumentation() string {
	if x != nil {
		return x.Documentation
	}
	return ""
}

func (x *Class) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *Class) GetDeprecatedReason() string {
	if x != nil {
		return x.DeprecatedReason
	}
	return ""
}

type Enumeration struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values           []*EnumerationValue    `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	Documentation    string                 `protobuf:"bytes,3,opt,name=documentation,proto3" json:"documentation,omitempty"`
	Deprecated       bool                   `protobuf:"varint,4,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	DeprecatedReason string                 `protobuf:"bytes,5,opt,name=deprecated_reason,json=deprecatedReason,proto3" json:"deprecated_reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Enumeration) Reset() {
	*x = Enumeration{}
	mi := &file_krpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enumeration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enumeration) ProtoMessage() {}

func (x *Enumeration) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enumeration.ProtoReflect.Descriptor instead.
func (*Enumeration) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{15}
}

func (x *Enumeration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Enumeration) GetValues() []*EnumerationValue {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Enumeration) GetDocumentation() string {
	if x != nil {
		return x.Documentation
	}
	return ""
}

func (x *Enumeration) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *Enumeration) GetDeprecatedReason() string {
	if x != nil {
		return x.DeprecatedReason
	}
	return ""
}

type EnumerationValue struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value            int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Documentation    string                 `protobuf:"bytes,3,opt,name=documentation,proto3" json:"documentation,omitempty"`
	Deprecated       bool                   `protobuf:"varint,4,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	DeprecatedReason string                 `protobuf:"bytes,5,opt,name=deprecated_reason,json=deprecatedReason,proto3" json:"deprecated_reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EnumerationValue) Reset() {
	*x = EnumerationValue{}
	mi := &file_krpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumerationValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerationValue) ProtoMessage() {}

func (x *EnumerationValue) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerationValue.ProtoReflect.Descriptor instead.
func (*EnumerationValue) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{16}
}

func (x *EnumerationValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnumerationValue) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *EnumerationValue) GetDocumentation() string {
	if x != nil {
		return x.Documentation
	}
	return ""
}

func (x *EnumerationValue) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *EnumerationValue) GetDeprecatedReason() string {
	if x != nil {
		return x.DeprecatedReason
	}
	return ""
}

type Exception struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Documentation    string                 `protobuf:"bytes,2,opt,name=documentation,proto3" json:"documentation,omitempty"`
	Deprecated       bool                   `protobuf:"varint,3,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	DeprecatedReason string                 `protobuf:"bytes,4,opt,name=deprecated_reason,json=deprecatedReason,proto3" json:"deprecated_reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Exception) Reset() {
	*x = Exception{}
	mi := &file_krpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exception) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exception) ProtoMessage() {}

func (x *Exception) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exception.ProtoReflect.Descriptor instead.
func (*Exception) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{17}
}

func (x *Exception) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Exception) GetDocumentation() string {
	if x != nil {
		return x.Documentation
	}
	return ""
}

func (x *Exception) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *Exception) GetDeprecatedReason() string {
	if x != nil {
		return x.DeprecatedReason
	}
	return ""
}

type Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Type_TypeCode          `protobuf:"varint,1,opt,name=code,proto3,enum=krpc.schema.Type_TypeCode" json:"code,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Types         []*Type                `protobuf:"bytes,4,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Type) Reset() {
	*x = Type{}
	mi := &file_krpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{18}
}

func (x *Type) GetCode() Type_TypeCode {
	if x != nil {
		return x.Code
	}
	return Type_NONE
}

func (x *Type) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Type) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Type) GetTypes() []*Type {
	if x != nil {
		return x.Types
	}
	return nil
}

type Tuple struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         [][]byte               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tuple) Reset() {
	*x = Tuple{}
	mi := &file_krpc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tuple) ProtoMessage() {}

func (x *Tuple) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tuple.ProtoReflect.Descriptor instead.
func (*Tuple) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{19}
}

func (x *Tuple) GetItems() [][]byte {
	if x != nil {
		return x.Items
	}
	return nil
}

type List struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         [][]byte               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *List) Reset() {
	*x = List{}
	mi := &file_krpc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List) ProtoMessage() {}

func (x *List) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List.ProtoReflect.Descriptor instead.
func (*List) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{20}
}

func (x *List) GetItems() [][]byte {
	if x != nil {
		return x.Items
	}
	return nil
}

type Set struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         [][]byte               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Set) Reset() {
	*x = Set{}
	mi := &file_krpc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Set) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Set) ProtoMessage() {}

func (x *Set) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Set.ProtoReflect.Descriptor instead.
func (*Set) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{21}
}

func (x *Set) GetItems() [][]byte {
	if x != nil {
		return x.Items
	}
	return nil
}

type Dictionary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DictionaryEntry     `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dictionary) Reset() {
	*x = Dictionary{}
	mi := &file_krpc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dictionary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dictionary) ProtoMessage() {}

func (x *Dictionary) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dictionary.ProtoReflect.Descriptor instead.
func (*Dictionary) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{22}
}

func (x *Dictionary) GetEntries() []*DictionaryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type DictionaryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictionaryEntry) Reset() {
	*x = DictionaryEntry{}
	mi := &file_krpc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictionaryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryEntry) ProtoMessage() {}

func (x *DictionaryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryEntry.ProtoReflect.Descriptor instead.
func (*DictionaryEntry) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{23}
}

func (x *DictionaryEntry) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DictionaryEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Stream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stream) Reset() {
	*x = Stream{}
	mi := &file_krpc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stream) ProtoMessage() {}

func (x *Stream) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stream.ProtoReflect.Descriptor instead.
func (*Stream) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{24}
}

func (x *Stream) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *Stream                `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_krpc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{25}
}

func (x *Event) GetStream() *Stream {
	if x != nil {
		return x.Stream
	}
	return nil
}

type Status struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Version              string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	BytesRead            uint64                 `protobuf:"varint,2,opt,name=bytes_read,json=bytesRead,proto3" json:"bytes_read,omitempty"`
	BytesWritten         uint64                 `protobuf:"varint,3,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	BytesReadRate        float32                `protobuf:"fixed32,4,opt,name=bytes_read_rate,json=bytesReadRate,proto3" json:"bytes_read_rate,omitempty"`
	BytesWrittenRate     float32                `protobuf:"fixed32,5,opt,name=bytes_written_rate,json=bytesWrittenRate,proto3" json:"bytes_written_rate,omitempty"`
	RpcsExecuted         uint64                 `protobuf:"varint,6,opt,name=rpcs_executed,json=rpcsExecuted,proto3" json:"rpcs_executed,omitempty"`
	RpcRate              float32                `protobuf:"fixed32,7,opt,name=rpc_rate,json=rpcRate,proto3" json:"rpc_rate,omitempty"`
	OneRpcPerUpdate      bool                   `protobuf:"varint,8,opt,name=one_rpc_per_update,json=oneRpcPerUpdate,proto3" json:"one_rpc_per_update,omitempty"`
	MaxTimePerUpdate     uint32                 `protobuf:"varint,9,opt,name=max_time_per_update,json=maxTimePerUpdate,proto3" json:"max_time_per_update,omitempty"`
	AdaptiveRateControl  bool                   `protobuf:"varint,10,opt,name=adaptive_rate_control,json=adaptiveRateControl,proto3" json:"adaptive_rate_control,omitempty"`
	BlockingRecv         bool                   `protobuf:"varint,11,opt,name=blocking_recv,json=blockingRecv,proto3" json:"blocking_recv,omitempty"`
	RecvTimeout          uint32                 `protobuf:"varint,12,opt,name=recv_timeout,json=recvTimeout,proto3" json:"recv_timeout,omitempty"`
	TimePerRpcUpdate     float32                `protobuf:"fixed32,13,opt,name=time_per_rpc_update,json=timePerRpcUpdate,proto3" json:"time_per_rpc_update,omitempty"`
	PollTimePerRpcUpdate float32                `protobuf:"fixed32,14,opt,name=poll_time_per_rpc_update,json=pollTimePerRpcUpdate,proto3" json:"poll_time_per_rpc_update,omitempty"`
	ExecTimePerRpcUpdate float32                `protobuf:"fixed32,15,opt,name=exec_time_per_rpc_update,json=execTimePerRpcUpdate,proto3" json:"exec_time_per_rpc_update,omitempty"`
	StreamRpcs           uint32                 `protobuf:"varint,16,opt,name=stream_rpcs,json=streamRpcs,proto3" json:"stream_rpcs,omitempty"`
	StreamRpcsExecuted   uint64                 `protobuf:"varint,17,opt,name=stream_rpcs_executed,json=streamRpcsExecuted,proto3" json:"stream_rpcs_executed,omitempty"`
	StreamRpcRate        float32                `protobuf:"fixed32,18,opt,name=stream_rpc_rate,json=streamRpcRate,proto3" json:"stream_rpc_rate,omitempty"`
	TimePerStreamUpdate  float32                `protobuf:"fixed32,19,opt,name=time_per_stream_update,json=timePerStreamUpdate,proto3" json:"time_per_stream_update,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_krpc_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{26}
}

func (x *Status) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Status) GetBytesRead() uint64 {
	if x != nil {
		return x.BytesRead
	}
	return 0
}

func (x *Status) GetBytesWritten() uint64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *Status) GetBytesReadRate() float32 {
	if x != nil {
		return x.BytesReadRate
	}
	return 0
}

func (x *Status) GetBytesWrittenRate() float32 {
	if x != nil {
		return x.BytesWrittenRate
	}
	return 0
}

func (x *Status) GetRpcsExecuted() uint64 {
	if x != nil {
		return x.RpcsExecuted
	}
	return 0
}

func (x *Status) GetRpcRate() float32 {
	if x != nil {
		return x.RpcRate
	}
	return 0
}

func (x *Status) GetOneRpcPerUpdate() bool {
	if x != nil {
		return x.OneRpcPerUpdate
	}
	return false
}

func (x *Status) GetMaxTimePerUpdate() uint32 {
	if x != nil {
		return x.MaxTimePerUpdate
	}
	return 0
}

func (x *Status) GetAdaptiveRateControl() bool {
	if x != nil {
		return x.AdaptiveRateControl
	}
	return false
}

func (x *Status) GetBlockingRecv() bool {
	if x != nil {
		return x.BlockingRecv
	}
	return false
}

func (x *Status) GetRecvTimeout() uint32 {
	if x != nil {
		return x.RecvTimeout
	}
	return 0
}

func (x *Status) GetTimePerRpcUpdate() float32 {
	if x != nil {
		return x.TimePerRpcUpdate
	}
	return 0
}

func (x *Status) GetPollTimePerRpcUpdate() float32 {
	if x != nil {
		return x.PollTimePerRpcUpdate
	}
	return 0
}

func (x *Status) GetExecTimePerRpcUpdate() float32 {
	if x != nil {
		return x.ExecTimePerRpcUpdate
	}
	return 0
}

func (x *Status) GetStreamRpcs() uint32 {
	if x != nil {
		return x.StreamRpcs
	}
	return 0
}

func (x *Status) GetStreamRpcsExecuted() uint64 {
	if x != nil {
		return x.StreamRpcsExecuted
	}
	return 0
}

func (x *Status) GetStreamRpcRate() float32 {
	if x != nil {
		return x.StreamRpcRate
	}
	return 0
}

func (x *Status) GetTimePerStreamUpdate() float32 {
	if x != nil {
		return x.TimePerStreamUpdate
	}
	return 0
}

type MultiplexedRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConnectionRequest *ConnectionRequest     `protobuf:"bytes,1,opt,name=connection_request,json=connectionRequest,proto3" json:"connection_request,omitempty"`
	Request           *Request               `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MultiplexedRequest) Reset() {
	*x = MultiplexedRequest{}
	mi := &file_krpc_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiplexedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiplexedRequest) ProtoMessage() {}

func (x *MultiplexedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiplexedRequest.ProtoReflect.Descriptor instead.
func (*MultiplexedRequest) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{27}
}

func (x *MultiplexedRequest) GetConnectionRequest() *ConnectionRequest {
	if x != nil {
		return x.ConnectionRequest
	}
	return nil
}

func (x *MultiplexedRequest) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type MultiplexedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	StreamUpdate  *StreamUpdate          `protobuf:"bytes,2,opt,name=stream_update,json=streamUpdate,proto3" json:"stream_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiplexedResponse) Reset() {
	*x = MultiplexedResponse{}
	mi := &file_krpc_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiplexedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiplexedResponse) ProtoMessage() {}

func (x *MultiplexedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_krpc_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiplexedResponse.ProtoReflect.Descriptor instead.
func (*MultiplexedResponse) Descriptor() ([]byte, []int) {
	return file_krpc_proto_rawDescGZIP(), []int{28}
}

func (x *MultiplexedResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *MultiplexedResponse) GetStreamUpdate() *StreamUpdate {
	if x != nil {
		return x.StreamUpdate
	}
	return nil
}

var File_krpc_proto protoreflect.FileDescriptor

const file_krpc_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"krpc.proto\x12\vkrpc.schema\"\xb7\x01\n" +
	"\x11ConnectionRequest\x127\n" +
	"\x04type\x18\x01 \x01(\x0e2#.krpc.schema.ConnectionRequest.TypeR\x04type\x12\x1f\n" +
	"\vclient_name\x18\x02 \x01(\tR\n" +
	"clientName\x12+\n" +
	"\x11client_identifier\x18\x03 \x01(\fR\x10clientIdentifier\"\x1b\n" +
	"\x04Type\x12\a\n" +
	"\x03RPC\x10\x00\x12\n" +
	"\n" +
	"\x06STREAM\x10\x01\"\xe1\x01\n" +
	"\x12ConnectionResponse\x12>\n" +
	"\x06status\x18\x01 \x01(\x0e2&.krpc.schema.ConnectionResponse.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x11client_identifier\x18\x03 \x01(\fR\x10clientIdentifier\"D\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\x15\n" +
	"\x11MALFORMED_MESSAGE\x10\x01\x12\v\n" +
	"\aTIMEOUT\x10\x02\x12\x0e\n" +
	"\n" +
	"WRONG_TYPE\x10\x03\";\n" +
	"\aRequest\x120\n" +
	"\x05calls\x18\x01 \x03(\v2\x1a.krpc.schema.ProcedureCallR\x05calls\"\xbe\x01\n" +
	"\rProcedureCall\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1c\n" +
	"\tprocedure\x18\x02 \x01(\tR\tprocedure\x12\x1d\n" +
	"\n" +
	"service_id\x18\x04 \x01(\rR\tserviceId\x12!\n" +
	"\fprocedure_id\x18\x05 \x01(\rR\vprocedureId\x123\n" +
	"\targuments\x18\x03 \x03(\v2\x15.krpc.schema.ArgumentR\targuments\"<\n" +
	"\bArgument\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\rR\bposition\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"l\n" +
	"\bResponse\x12(\n" +
	"\x05error\x18\x01 \x01(\v2\x12.krpc.schema.ErrorR\x05error\x126\n" +
	"\aresults\x18\x02 \x03(\v2\x1c.krpc.schema.ProcedureResultR\aresults\"Q\n" +
	"\x0fProcedureResult\x12(\n" +
	"\x05error\x18\x01 \x01(\v2\x12.krpc.schema.ErrorR\x05error\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"x\n" +
	"\x05Error\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vstack_trace\x18\x04 \x01(\tR\n" +
	"stackTrace\"C\n" +
	"\fStreamUpdate\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.krpc.schema.StreamResultR\aresults\"T\n" +
	"\fStreamResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x124\n" +
	"\x06result\x18\x02 \x01(\v2\x1c.krpc.schema.ProcedureResultR\x06result\"<\n" +
	"\bServices\x120\n" +
	"\bservices\x18\x01 \x03(\v2\x14.krpc.schema.ServiceR\bservices\"\xec\x02\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x126\n" +
	"\n" +
	"procedures\x18\x02 \x03(\v2\x16.krpc.schema.ProcedureR\n" +
	"procedures\x12,\n" +
	"\aclasses\x18\x03 \x03(\v2\x12.krpc.schema.ClassR\aclasses\x12<\n" +
	"\fenumerations\x18\x04 \x03(\v2\x18.krpc.schema.EnumerationR\fenumerations\x126\n" +
	"\n" +
	"exceptions\x18\x05 \x03(\v2\x16.krpc.schema.ExceptionR\n" +
	"exceptions\x12$\n" +
	"\rdocumentation\x18\x06 \x01(\tR\rdocumentation\x12\x1e\n" +
	"\n" +
	"deprecated\x18\a \x01(\bR\n" +
	"deprecated\x12+\n" +
	"\x11deprecated_reason\x18\b \x01(\tR\x10deprecatedReason\"\xe5\x03\n" +
	"\tProcedure\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x126\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2\x16.krpc.schema.ParameterR\n" +
	"parameters\x122\n" +
	"\vreturn_type\x18\x03 \x01(\v2\x11.krpc.schema.TypeR\n" +
	"returnType\x12,\n" +
	"\x12return_is_nullable\x18\x04 \x01(\bR\x10returnIsNullable\x12A\n" +
	"\vgame_scenes\x18\x06 \x03(\x0e2 .krpc.schema.Procedure.GameSceneR\n" +
	"gameScenes\x12$\n" +
	"\rdocumentation\x18\x05 \x01(\tR\rdocumentation\x12\x1e\n" +
	"\n" +
	"deprecated\x18\a \x01(\bR\n" +
	"deprecated\x12+\n" +
	"\x11deprecated_reason\x18\b \x01(\tR\x10deprecatedReason\"t\n" +
	"\tGameScene\x12\x10\n" +
	"\fSPACE_CENTER\x10\x00\x12\n" +
	"\n" +
	"\x06FLIGHT\x10\x01\x12\x14\n" +
	"\x10TRACKING_STATION\x10\x02\x12\x0e\n" +
	"\n" +
	"EDITOR_VAB\x10\x03\x12\x0e\n" +
	"\n" +
	"EDITOR_SPH\x10\x04\x12\x13\n" +
	"\x0fMISSION_BUILDER\x10\x05\"\x87\x01\n" +
	"\tParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x02 \x01(\v2\x11.krpc.schema.TypeR\x04type\x12#\n" +
	"\rdefault_value\x18\x03 \x01(\fR\fdefaultValue\x12\x1a\n" +
	"\bnullable\x18\x04 \x01(\bR\bnullable\"\x8e\x01\n" +
	"\x05Class\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12$\n" +
	"\rdocumentation\x18\x02 \x01(\tR\rdocumentation\x12\x1e\n" +
	"\n" +
	"deprecated\x18\x03 \x01(\bR\n" +
	"deprecated\x12+\n" +
	"\x11deprecated_reason\x18\x04 \x01(\tR\x10deprecatedReason\"\xcb\x01\n" +
	"\vEnumeration\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\x06values\x18\x02 \x03(\v2\x1d.krpc.schema.EnumerationValueR\x06values\x12$\n" +
	"\rdocumentation\x18\x03 \x01(\tR\rdocumentation\x12\x1e\n" +
	"\n" +
	"deprecated\x18\x04 \x01(\bR\n" +
	"deprecated\x12+\n" +
	"\x11deprecated_reason\x18\x05 \x01(\tR\x10deprecatedReason\"\xaf\x01\n" +
	"\x10EnumerationValue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\x12$\n" +
	"\rdocumentation\x18\x03 \x01(\tR\rdocumentation\x12\x1e\n" +
	"\n" +
	"deprecated\x18\x04 \x01(\bR\n" +
	"deprecated\x12+\n" +
	"\x11deprecated_reason\x18\x05 \x01(\tR\x10deprecatedReason\"\x92\x01\n" +
	"\tException\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12$\n" +
	"\rdocumentation\x18\x02 \x01(\tR\rdocumentation\x12\x1e\n" +
	"\n" +
	"deprecated\x18\x03 \x01(\bR\n" +
	"deprecated\x12+\n" +
	"\x11deprecated_reason\x18\x04 \x01(\tR\x10deprecatedReason\"\xa4\x03\n" +
	"\x04Type\x12.\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1a.krpc.schema.Type.TypeCodeR\x04code\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12'\n" +
	"\x05types\x18\x04 \x03(\v2\x11.krpc.schema.TypeR\x05types\"\x94\x02\n" +
	"\bTypeCode\x12\b\n" +
	"\x04NONE\x10\x00\x12\n" +
	"\n" +
	"\x06DOUBLE\x10\x01\x12\t\n" +
	"\x05FLOAT\x10\x02\x12\n" +
	"\n" +
	"\x06SINT32\x10\x03\x12\n" +
	"\n" +
	"\x06SINT64\x10\x04\x12\n" +
	"\n" +
	"\x06UINT32\x10\x05\x12\n" +
	"\n" +
	"\x06UINT64\x10\x06\x12\b\n" +
	"\x04BOOL\x10\a\x12\n" +
	"\n" +
	"\x06STRING\x10\b\x12\t\n" +
	"\x05BYTES\x10\t\x12\t\n" +
	"\x05CLASS\x10d\x12\x0f\n" +
	"\vENUMERATION\x10e\x12\n" +
	"\n" +
	"\x05EVENT\x10\xc8\x01\x12\x13\n" +
	"\x0ePROCEDURE_CALL\x10\xc9\x01\x12\v\n" +
	"\x06STREAM\x10\xca\x01\x12\v\n" +
	"\x06STATUS\x10\xcb\x01\x12\r\n" +
	"\bSERVICES\x10\xcc\x01\x12\n" +
	"\n" +
	"\x05TUPLE\x10\xac\x02\x12\t\n" +
	"\x04LIST\x10\xad\x02\x12\b\n" +
	"\x03SET\x10\xae\x02\x12\x0f\n" +
	"\n" +
	"DICTIONARY\x10\xaf\x02\"\x1d\n" +
	"\x05Tuple\x12\x14\n" +
	"\x05items\x18\x01 \x03(\fR\x05items\"\x1c\n" +
	"\x04List\x12\x14\n" +
	"\x05items\x18\x01 \x03(\fR\x05items\"\x1b\n" +
	"\x03Set\x12\x14\n" +
	"\x05items\x18\x01 \x03(\fR\x05items\"D\n" +
	"\n" +
	"Dictionary\x126\n" +
	"\aentries\x18\x01 \x03(\v2\x1c.krpc.schema.DictionaryEntryR\aentries\"9\n" +
	"\x0fDictionaryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x18\n" +
	"\x06Stream\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"4\n" +
	"\x05Event\x12+\n" +
	"\x06stream\x18\x01 \x01(\v2\x13.krpc.schema.StreamR\x06stream\"\xa3\x06\n" +
	"\x06Status\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"bytes_read\x18\x02 \x01(\x04R\tbytesRead\x12#\n" +
	"\rbytes_written\x18\x03 \x01(\x04R\fbytesWritten\x12&\n" +
	"\x0fbytes_read_rate\x18\x04 \x01(\x02R\rbytesReadRate\x12,\n" +
	"\x12bytes_written_rate\x18\x05 \x01(\x02R\x10bytesWrittenRate\x12#\n" +
	"\rrpcs_executed\x18\x06 \x01(\x04R\frpcsExecuted\x12\x19\n" +
	"\brpc_rate\x18\a \x01(\x02R\arpcRate\x12+\n" +
	"\x12one_rpc_per_update\x18\b \x01(\bR\x0foneRpcPerUpdate\x12-\n" +
	"\x13max_time_per_update\x18\t \x01(\rR\x10maxTimePerUpdate\x122\n" +
	"\x15adaptive_rate_control\x18\n" +
	" \x01(\bR\x13adaptiveRateControl\x12#\n" +
	"\rblocking_recv\x18\v \x01(\bR\fblockingRecv\x12!\n" +
	"\frecv_timeout\x18\f \x01(\rR\vrecvTimeout\x12-\n" +
	"\x13time_per_rpc_update\x18\r \x01(\x02R\x10timePerRpcUpdate\x126\n" +
	"\x18poll_time_per_rpc_update\x18\x0e \x01(\x02R\x14pollTimePerRpcUpdate\x126\n" +
	"\x18exec_time_per_rpc_update\x18\x0f \x01(\x02R\x14execTimePerRpcUpdate\x12\x1f\n" +
	"\vstream_rpcs\x18\x10 \x01(\rR\n" +
	"streamRpcs\x120\n" +
	"\x14stream_rpcs_executed\x18\x11 \x01(\x04R\x12streamRpcsExecuted\x12&\n" +
	"\x0fstream_rpc_rate\x18\x12 \x01(\x02R\rstreamRpcRate\x123\n" +
	"\x16time_per_stream_update\x18\x13 \x01(\x02R\x13timePerStreamUpdate\"\x93\x01\n" +
	"\x12MultiplexedRequest\x12M\n" +
	"\x12connection_request\x18\x01 \x01(\v2\x1e.krpc.schema.ConnectionRequestR\x11connectionRequest\x12.\n" +
	"\arequest\x18\x02 \x01(\v2\x14.krpc.schema.RequestR\arequest\"\x88\x01\n" +
	"\x13MultiplexedResponse\x121\n" +
	"\bresponse\x18\x01 \x01(\v2\x15.krpc.schema.ResponseR\bresponse\x12>\n" +
	"\rstream_update\x18\x02 \x01(\v2\x19.krpc.schema.StreamUpdateR\fstreamUpdateBV\n" +
	"\vkrpc.schemaB\x04KRPCH\x03Z%github.com/cpuchip/ksp-hmi/krpc/pb;pb\xa2\x02\x04KRPC\xaa\x02\x10KRPC.Schema.KRPCb\x06proto3"

var (
	file_krpc_proto_rawDescOnce sync.Once
	file_krpc_proto_rawDescData []byte
)

func file_krpc_proto_rawDescGZIP() []byte {
	file_krpc_proto_rawDescOnce.Do(func() {
		file_krpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_krpc_proto_rawDesc), len(file_krpc_proto_rawDesc)))
	})
	return file_krpc_proto_rawDescData
}

var file_krpc_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_krpc_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_krpc_proto_goTypes = []any{
	(ConnectionRequest_Type)(0),    // 0: krpc.schema.ConnectionRequest.Type
	(ConnectionResponse_Status)(0), // 1: krpc.schema.ConnectionResponse.Status
	(Procedure_GameScene)(0),       // 2: krpc.schema.Procedure.GameScene
	(Type_TypeCode)(0),             // 3: krpc.schema.Type.TypeCode
	(*ConnectionRequest)(nil),      // 4: krpc.schema.ConnectionRequest
	(*ConnectionResponse)(nil),     // 5: krpc.schema.ConnectionResponse
	(*Request)(nil),                // 6: krpc.schema.Request
	(*ProcedureCall)(nil),          // 7: krpc.schema.ProcedureCall
	(*Argument)(nil),               // 8: krpc.schema.Argument
	(*Response)(nil),               // 9: krpc.schema.Response
	(*ProcedureResult)(nil),        // 10: krpc.schema.ProcedureResult
	(*Error)(nil),                  // 11: krpc.schema.Error
	(*StreamUpdate)(nil),           // 12: krpc.schema.StreamUpdate
	(*StreamResult)(nil),           // 13: krpc.schema.StreamResult
	(*Services)(nil),               // 14: krpc.schema.Services
	(*Service)(nil),                // 15: krpc.schema.Service
	(*Procedure)(nil),              // 16: krpc.schema.Procedure
	(*Parameter)(nil),              // 17: krpc.schema.Parameter
	(*Class)(nil),                  // 18: krpc.schema.Class
	(*Enumeration)(nil),            // 19: krpc.schema.Enumeration
	(*EnumerationValue)(nil),       // 20: krpc.schema.EnumerationValue
	(*Exception)(nil),              // 21: krpc.schema.Exception
	(*Type)(nil),                   // 22: krpc.schema.Type
	(*Tuple)(nil),                  // 23: krpc.schema.Tuple
	(*List)(nil),                   // 24: krpc.schema.List
	(*Set)(nil),                    // 25: krpc.schema.Set
	(*Dictionary)(nil),             // 26: krpc.schema.Dictionary
	(*DictionaryEntry)(nil),        // 27: krpc.schema.DictionaryEntry
	(*Stream)(nil),                 // 28: krpc.schema.Stream
	(*Event)(nil),                  // 29: krpc.schema.Event
	(*Status)(nil),                 // 30: krpc.schema.Status
	(*MultiplexedRequest)(nil),     // 31: krpc.schema.MultiplexedRequest
	(*MultiplexedResponse)(nil),    // 32: krpc.schema.MultiplexedResponse
}
var file_krpc_proto_depIdxs = []int32{
	0,  // 0: krpc.schema.ConnectionRequest.type:type_name -> krpc.schema.ConnectionRequest.Type
	1,  // 1: krpc.schema.ConnectionResponse.status:type_name -> krpc.schema.ConnectionResponse.Status
	7,  // 2: krpc.schema.Request.calls:type_name -> krpc.schema.ProcedureCall
	8,  // 3: krpc.schema.ProcedureCall.arguments:type_name -> krpc.schema.Argument
	11, // 4: krpc.schema.Response.error:type_name -> krpc.schema.Error
	10, // 5: krpc.schema.Response.results:type_name -> krpc.schema.ProcedureResult
	11, // 6: krpc.schema.ProcedureResult.error:type_name -> krpc.schema.Error
	13, // 7: krpc.schema.StreamUpdate.results:type_name -> krpc.schema.StreamResult
	10, // 8: krpc.schema.StreamResult.result:type_name -> krpc.schema.ProcedureResult
	15, // 9: krpc.schema.Services.services:type_name -> krpc.schema.Service
	16, // 10: krpc.schema.Service.procedures:type_name -> krpc.schema.Procedure
	18, // 11: krpc.schema.Service.classes:type_name -> krpc.schema.Class
	19, // 12: krpc.schema.Service.enumerations:type_name -> krpc.schema.Enumeration
	21, // 13: krpc.schema.Service.exceptions:type_name -> krpc.schema.Exception
	17, // 14: krpc.schema.Procedure.parameters:type_name -> krpc.schema.Parameter
	22, // 15: krpc.schema.Procedure.return_type:type_name -> krpc.schema.Type
	2,  // 16: krpc.schema.Procedure.game_scenes:type_name -> krpc.schema.Procedure.GameScene
	22, // 17: krpc.schema.Parameter.type:type_name -> krpc.schema.Type
	20, // 18: krpc.schema.Enumeration.values:type_name -> krpc.schema.EnumerationValue
	3,  // 19: krpc.schema.Type.code:type_name -> krpc.schema.Type.TypeCode
	22, // 20: krpc.schema.Type.types:type_name -> krpc.schema.Type
	27, // 21: krpc.schema.Dictionary.entries:type_name -> krpc.schema.DictionaryEntry
	28, // 22: krpc.schema.Event.stream:type_name -> krpc.schema.Stream
	4,  // 23: krpc.schema.MultiplexedRequest.connection_request:type_name -> krpc.schema.ConnectionRequest
	6,  // 24: krpc.schema.MultiplexedRequest.request:type_name -> krpc.schema.Request
	9,  // 25: krpc.schema.MultiplexedResponse.response:type_name -> krpc.schema.Response
	12, // 26: krpc.schema.MultiplexedResponse.stream_update:type_name -> krpc.schema.StreamUpdate
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_krpc_proto_init() }
func file_krpc_proto_init() {
	if File_krpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_krpc_proto_rawDesc), len(file_krpc_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_krpc_proto_goTypes,
		DependencyIndexes: file_krpc_proto_depIdxs,
		EnumInfos:         file_krpc_proto_enumTypes,
		MessageInfos:      file_krpc_proto_msgTypes,
	}.Build()
	File_krpc_proto = out.File
	file_krpc_proto_goTypes = nil
	file_krpc_proto_depIdxs = nil
}
